yellow:
  A:
    ip: 127.0.0.1
    port: 50514
    grSimID: 0
    shellID: 0
    has_chip_kick: false
  B:
    ip: 192.168.1.7
    port: 50514
    grSimID: 1
    shellID: 1
    has_chip_kick: false
  C:
    ip: 127.0.0.1
    port: 50514
    grSimID: 2
    shellID: 2
    has_chip_kick: false
  D:
    ip: 192.168.1.4
    port: 50514
    grSimID: 3
    shellID: 3
    has_chip_kick: false
  E:
    ip: 127.0.0.1
    port: 50514
    grSimID: 4
    shellID: 4
    has_chip_kick: false
  F:
    ip: 127.0.0.1
    port: 50514
    grSimID: 5
    shellID: 5
    has_chip_kick: false
blue:
  A:
    ip: 127.0.0.1
    port: 12345
    grSimID: 0
    shellID: 0
    has_chip_kick: false
  B:
    ip: 192.168.1.4
    port: 50514
    grSimID: 1
    shellID: 1
    has_chip_kick: false
  C:
    ip: 127.0.0.1
    port: 50514
    grSimID: 2
    shellID: 2
    has_chip_kick: false
  D:
    ip: 127.0.0.1
    port: 50514
    grSimID: 3
    shellID: 3
    has_chip_kick: false
  E:
    ip: 127.0.0.1
    port: 50514
    grSimID: 4
    shellID: 4
    has_chip_kick: false
  F:
    ip: 127.0.0.1
    port: 50514
    grSimID: 5
    shellID: 5
    has_chip_kick: false
grSim:
  ip: 127.0.0.1
  port: 20011
vision:
  multicast-group: 224.5.23.2
  port: 10006
gc:
  multicast-group: 224.5.23.1
  port: 10003
network:
  robot_ip: 192.168.1.2
  vision_ip: 192.168.1.2
use_grSim_vision: false
us_yellow: true
us_positive: true
send_to_grSim: false
